const ACTIONS = {
  LOGIN: "LOGIN",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_ADMIN_TOKEN: "GET_ADMIN_TOKEN",
  DELETE_TOKEN: "DELETE_TOKEN",
  GET_DOCTOR: "GET_DOCTOR",
  GET_ADMIN: "GET_ADMIN",
  DELETE: "DELETE",
  GET_ALL_DOCTORS: "GET_ALL_DOCTORS",
};

export default ACTIONS;
